### ISSUE TITLE
Documentation of Re-exports is missing

### ISSUE THREAD

**Issue by hanjoosten** [commercialhaskell/rio-prettyprint#2]
The [documentation of rio-prettyprint](https://hackage.haskell.org/package/rio-prettyprint-0.1.0.0/docs/RIO-PrettyPrint.html#g:7) should contain the same documentation as [the original definitions](https://hackage.haskell.org/package/ansi-wl-pprint-0.6.9/docs/Text-PrettyPrint-ANSI-Leijen.html#g:6) that it re-exports. 
I am not sure there is a feature in haddock that supports this. If not, this is a good usecase to request such a feature.

**Comment by mpilgrem** [comment]
@hanjoosten, agreed on the documentation. The problem is that the 're-exports' are not, in fact, re-exports. They are isomorphic - for example `nest :: Int -> Doc a -> Doc a` becomes `nest :: Int -> StyleDoc -> StyleDoc`.
