### ISSUE TITLE
  HasTerm instance form SimpleApp

### ISSUE THREAD

**Issue by yaitskov** [commercialhaskell/rio-prettyprint#6]
Hi,

I cannot find HasTerm instance for SimpleApp. 
It would be nice to have it in the library because class HasTerm is defined here and avoid orphan warning.

**Comment by snoyberg** [comment]
Seems reasonable, want to send a PR?

**Comment by yaitskov** [comment]
https://github.com/commercialhaskell/rio-prettyprint/pull/7

**Comment by mpilgrem** [comment]
I've come to this issue late, after having proposed pull request #12. I've taken a different approach to solving a very similar problem: I've proposed a `SimplePrettyApp` type exported by this package, with its two related functions.

**Comment by mpilgrem** [comment]
I am going to close this issue, as `rio-prettyprint-0.1.3.0` provides `SimplePrettyApp` which is an instance of `HasTerm`.
